source 'https://rubygems.org'
gem 'httpclient', '2.8.2.4'
gem 'cucumber', '2.4.0'
gem 'rest-client', '1.8.0'
gem 'docker-compose','1.0.0'
gem 'rspec'
gem 'rspec-expectations'
gem 'rspec-core'
gem 'rspec-mocks'
gem 'simplecov'
gem 'mustache'